name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Update package-lock.json
      run: npm install --package-lock-only
    
    - name: Install dependencies
      run: npm install
      
    - name: Create test environment file
      run: |
        echo "GOOGLE_CLIENT_ID=test-client-id-for-ci" > .env
        echo "GOOGLE_CLIENT_SECRET=test-client-secret-for-ci" >> .env
        echo "GOOGLE_REDIRECT_URI=http://localhost:4153/oauth2callback" >> .env
        echo "NODE_ENV=test" >> .env
    
    - name: TypeScript Check
      run: npx tsc --noEmit
    
    - name: Lint
      run: npm run lint
    
    - name: Build
      run: npm run build
      env:
        NODE_ENV: test
        GOOGLE_CLIENT_ID: test-client-id-for-ci
        GOOGLE_CLIENT_SECRET: test-client-secret-for-ci
      
    - name: Test
      run: npm test
      env:
        NODE_ENV: test
        GOOGLE_CLIENT_ID: test-client-id-for-ci
        GOOGLE_CLIENT_SECRET: test-client-secret-for-ci