# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # 毎週日曜日に実行

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --production

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test environment file
        run: |
          echo "GOOGLE_CLIENT_ID=test-client-id-for-main" > .env
          echo "GOOGLE_CLIENT_SECRET=test-client-secret-for-main" >> .env
          echo "GOOGLE_REDIRECT_URI=http://localhost:4153/oauth2callback" >> .env
          echo "NODE_ENV=test" >> .env

      - name: Run tests
        run: npm test -- --coverage
        env:
          NODE_ENV: test
          GOOGLE_CLIENT_ID: test-client-id-for-main
          GOOGLE_CLIENT_SECRET: test-client-secret-for-main

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, security, test]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create test environment file
        run: |
          echo "GOOGLE_CLIENT_ID=test-client-id-for-build" > .env
          echo "GOOGLE_CLIENT_SECRET=test-client-secret-for-build" >> .env
          echo "GOOGLE_REDIRECT_URI=http://localhost:4153/oauth2callback" >> .env
          echo "NODE_ENV=test" >> .env

      - name: Build
        run: npm run build
        env:
          NODE_ENV: test
          GOOGLE_CLIENT_ID: test-client-id-for-build
          GOOGLE_CLIENT_SECRET: test-client-secret-for-build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # リリースジョブ - mainブランチのみ実行
  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      # 自動バージョン更新（必要に応じてコメントアウト）
      # - name: Bump version
      #   id: bump_version
      #   uses: phips28/gh-action-bump-version@master
      #   with:
      #     tag-prefix: 'v'
      #     minor-wording: 'feat,feature'
      #     major-wording: 'BREAKING,major'
      #     patch-wording: 'fix,patch'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # NPMパッケージとして公開（必要に応じてコメントアウト）
      # - name: Publish to NPM
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
