name: Publish Package to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Create test environment file  
        run: |
          echo "GOOGLE_CLIENT_ID=test-client-id-for-publish" > .env
          echo "GOOGLE_CLIENT_SECRET=test-client-secret-for-publish" >> .env
          echo "GOOGLE_REDIRECT_URI=http://localhost:4153/oauth2callback" >> .env
          echo "NODE_ENV=test" >> .env
      
      - name: Build
        run: npm run build
        env:
          NODE_ENV: test
          GOOGLE_CLIENT_ID: test-client-id-for-publish
          GOOGLE_CLIENT_SECRET: test-client-secret-for-publish
      
      - name: Test
        run: npm test
        env:
          NODE_ENV: test
          GOOGLE_CLIENT_ID: test-client-id-for-publish
          GOOGLE_CLIENT_SECRET: test-client-secret-for-publish
      
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
